spring.datasource.url: jdbc:mysql://localhost:3306/wardrobe
spring.datasource.username: root
spring.datasource.password: Ybrbnf
spring.jpa.hibernate.ddl-auto: create
spring.mustache.expose-request-attributes: