spring.datasource.url: jdbc:mysql://localhost:3306/wardrobe
spring.datasource.username: root
spring.datasource.password: Ybrbnf
spring.jpa.hibernate.ddl-auto: update
spring.mustache.expose-request-attributes: update

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.main.allow-circular-references: true
spring.mail.host: smtp.yandex.ru
spring.mail.username: admin@wardrobe.com
spring.mail.password: 12345678
spring.mail.port: 465
spring.mail.protocol: smtps
mail.debug: true
recaptcha.secret: 6LeG9XokAAAAAD8jpbJQvvz94b_QOmk4yV8eI97o


